<?php
/**
 * TransactionsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  YNAB\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * YNAB API Endpoints
 *
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace YNAB\Api;

use \YNAB\Api\Configuration;
use \YNAB\Api\ApiException;
use \YNAB\Api\ObjectSerializer;

/**
 * TransactionsApiTest Class Doc Comment
 *
 * @category Class
 * @package  YNAB\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TransactionsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for bulkCreateTransactions
     *
     * Bulk create transactions.
     *
     */
    public function testBulkCreateTransactions()
    {
    }

    /**
     * Test case for createTransaction
     *
     * Create new transaction.
     *
     */
    public function testCreateTransaction()
    {
    }

    /**
     * Test case for getTransactions
     *
     * List transactions.
     *
     */
    public function testGetTransactions()
    {
    }

    /**
     * Test case for getTransactionsByAccount
     *
     * List account transactions.
     *
     */
    public function testGetTransactionsByAccount()
    {
    }

    /**
     * Test case for getTransactionsByCategory
     *
     * List category transactions.
     *
     */
    public function testGetTransactionsByCategory()
    {
    }

    /**
     * Test case for getTransactionsById
     *
     * Single transaction.
     *
     */
    public function testGetTransactionsById()
    {
    }

    /**
     * Test case for getTransactionsByPayee
     *
     * List payee transactions.
     *
     */
    public function testGetTransactionsByPayee()
    {
    }

    /**
     * Test case for updateTransaction
     *
     * Updates an existing transaction.
     *
     */
    public function testUpdateTransaction()
    {
    }
}
